const { Router } = require("express");
const adminRoutes = require("./adminRoutes");
const authRoutes = require("./authRoutes");
const categoryRoutes = require("./categoryRoutes");
const gamificationRoutes = require("./gamificationRoutes");
const profileRoutes = require("./profileRoutes");
const weightRoutes = require("./weightRoutes");
const workoutRoutes = require("./workoutRoutes");
const templateRoutes = require("./templateRoutes");
const feedbackRoutes = require("./feedbackRoutes");
const challengeRoutes = require("./challengeRoutes");
const announcementRoutes = require("./announcementRoutes");
const weeklyPlanRoutes = require("./weeklyPlanRoutes");
const progressRoutes = require("./progressRoutes");
const aiRoutes = require("./aiRoutes");
const exerciseRoutes = require("./exerciseRoutes");
const activityLibraryRoutes = require("./activityLibraryRoutes");
const nutritionRoutes = require("./nutritionRoutes");

const router = Router();

router.use("/auth", authRoutes);
router.use("/profile", profileRoutes);
router.use("/workouts", workoutRoutes);
router.use("/weights", weightRoutes);
router.use("/categories", categoryRoutes);
router.use("/exercises", exerciseRoutes);
router.use("/gamification", gamificationRoutes);
router.use("/templates", templateRoutes);
router.use("/feedback", feedbackRoutes);
router.use("/challenges", challengeRoutes);
router.use("/announcements", announcementRoutes);
router.use("/admin", adminRoutes);
router.use("/weekly-plan", weeklyPlanRoutes);
router.use("/progress", progressRoutes);
router.use("/insights", aiRoutes);
router.use("/activity-library", activityLibraryRoutes);
router.use("/nutrition", nutritionRoutes);

module.exports = router;
