-- Migration 0010: Seed 125 default activities into exercise_library
USE fitsync_db;

INSERT INTO exercise_library
  (id, name, category_id, muscle_group, equipment, exercise_type, default_duration, is_custom)
VALUES
  ('act-push-up', 'Push Up', 'cat_strength', 'Chest', 'Bodyweight', 'strength', 10, FALSE),
  ('act-knee-push-up', 'Knee Push Up', 'cat_strength', 'Chest', 'Bodyweight', 'strength', 10, FALSE),
  ('act-pull-up', 'Pull Up', 'cat_strength', 'Back', 'Bodyweight', 'strength', 10, FALSE),
  ('act-chin-up', 'Chin Up', 'cat_strength', 'Back', 'Bodyweight', 'strength', 10, FALSE),
  ('act-squat', 'Squat', 'cat_strength', 'Legs', 'Bodyweight', 'strength', 10, FALSE),
  ('act-goblet-squat', 'Goblet Squat', 'cat_strength', 'Legs', 'Dumbbell', 'strength', 10, FALSE),
  ('act-barbell-squat', 'Barbell Squat', 'cat_strength', 'Legs', 'Barbell', 'strength', 10, FALSE),
  ('act-deadlift', 'Deadlift', 'cat_strength', 'Posterior Chain', 'Barbell', 'strength', 10, FALSE),
  ('act-romanian-deadlift', 'Romanian Deadlift', 'cat_strength', 'Posterior Chain', 'Barbell', 'strength', 10, FALSE),
  ('act-bench-press', 'Bench Press', 'cat_strength', 'Chest', 'Barbell', 'strength', 10, FALSE),
  ('act-incline-bench-press', 'Incline Bench Press', 'cat_strength', 'Chest', 'Barbell', 'strength', 10, FALSE),
  ('act-dumbbell-bench-press', 'Dumbbell Bench Press', 'cat_strength', 'Chest', 'Dumbbell', 'strength', 10, FALSE),
  ('act-shoulder-press', 'Shoulder Press', 'cat_strength', 'Shoulders', 'Dumbbell', 'strength', 10, FALSE),
  ('act-lateral-raise', 'Lateral Raise', 'cat_strength', 'Shoulders', 'Dumbbell', 'strength', 10, FALSE),
  ('act-bicep-curl', 'Bicep Curl', 'cat_strength', 'Arms', 'Dumbbell', 'strength', 10, FALSE),
  ('act-hammer-curl', 'Hammer Curl', 'cat_strength', 'Arms', 'Dumbbell', 'strength', 10, FALSE),
  ('act-tricep-extension', 'Tricep Extension', 'cat_strength', 'Arms', 'Dumbbell', 'strength', 10, FALSE),
  ('act-dip', 'Dip', 'cat_strength', 'Arms', 'Bodyweight', 'strength', 10, FALSE),
  ('act-plank', 'Plank', 'cat_strength', 'Core', 'Bodyweight', 'strength', 10, FALSE),
  ('act-lunge', 'Lunge', 'cat_strength', 'Legs', 'Bodyweight', 'strength', 10, FALSE),
  ('act-leg-press', 'Leg Press', 'cat_strength', 'Legs', 'Machine', 'strength', 10, FALSE),
  ('act-leg-curl', 'Leg Curl', 'cat_strength', 'Legs', 'Machine', 'strength', 10, FALSE),
  ('act-calf-raise', 'Calf Raise', 'cat_strength', 'Legs', 'Bodyweight', 'strength', 10, FALSE),
  ('act-barbell-row', 'Barbell Row', 'cat_strength', 'Back', 'Barbell', 'strength', 10, FALSE),
  ('act-dumbbell-row', 'Dumbbell Row', 'cat_strength', 'Back', 'Dumbbell', 'strength', 10, FALSE),
  ('act-lat-pulldown', 'Lat Pulldown', 'cat_strength', 'Back', 'Machine', 'strength', 10, FALSE),
  ('act-cable-row', 'Cable Row', 'cat_strength', 'Back', 'Machine', 'strength', 10, FALSE),
  ('act-hip-thrust', 'Hip Thrust', 'cat_strength', 'Glutes', 'Barbell', 'strength', 10, FALSE),
  ('act-glute-bridge', 'Glute Bridge', 'cat_strength', 'Glutes', 'Bodyweight', 'strength', 10, FALSE),
  ('act-crunch', 'Crunch', 'cat_strength', 'Core', 'Bodyweight', 'strength', 10, FALSE),
  ('act-russian-twist', 'Russian Twist', 'cat_strength', 'Core', 'Bodyweight', 'strength', 10, FALSE),
  ('act-leg-raise', 'Leg Raise', 'cat_strength', 'Core', 'Bodyweight', 'strength', 10, FALSE),
  ('act-farmer-carry', 'Farmer Carry', 'cat_strength', 'Full Body', 'Dumbbell', 'strength', 10, FALSE),
  ('act-kettlebell-swing', 'Kettlebell Swing', 'cat_strength', 'Full Body', 'Kettlebell', 'strength', 10, FALSE),
  ('act-clean-and-press', 'Clean and Press', 'cat_strength', 'Full Body', 'Barbell', 'strength', 10, FALSE),
  ('act-front-squat', 'Front Squat', 'cat_strength', 'Legs', 'Barbell', 'strength', 10, FALSE),
  ('act-bulgarian-split-squat', 'Bulgarian Split Squat', 'cat_strength', 'Legs', 'Dumbbell', 'strength', 10, FALSE),
  ('act-chest-fly', 'Chest Fly', 'cat_strength', 'Chest', 'Dumbbell', 'strength', 10, FALSE),
  ('act-face-pull', 'Face Pull', 'cat_strength', 'Shoulders', 'Machine', 'strength', 10, FALSE),
  ('act-shrug', 'Shrug', 'cat_strength', 'Shoulders', 'Dumbbell', 'strength', 10, FALSE),
  ('act-overhead-press', 'Overhead Press', 'cat_strength', 'Shoulders', 'Barbell', 'strength', 10, FALSE),
  ('act-leg-extension', 'Leg Extension', 'cat_strength', 'Legs', 'Machine', 'strength', 10, FALSE),

  ('act-running', 'Running', 'cat_cardio', 'Cardio', 'Outdoor', 'cardio', 10, FALSE),
  ('act-jogging', 'Jogging', 'cat_cardio', 'Cardio', 'Outdoor', 'cardio', 10, FALSE),
  ('act-walking', 'Walking', 'cat_cardio', 'Cardio', 'Outdoor', 'cardio', 10, FALSE),
  ('act-treadmill', 'Treadmill', 'cat_cardio', 'Cardio', 'Machine', 'cardio', 10, FALSE),
  ('act-cycling', 'Cycling', 'cat_cardio', 'Cardio', 'Outdoor', 'cardio', 10, FALSE),
  ('act-stationary-bike', 'Stationary Bike', 'cat_cardio', 'Cardio', 'Machine', 'cardio', 10, FALSE),
  ('act-jump-rope', 'Jump Rope', 'cat_cardio', 'Cardio', 'Rope', 'cardio', 10, FALSE),
  ('act-rowing-machine', 'Rowing Machine', 'cat_cardio', 'Cardio', 'Machine', 'cardio', 10, FALSE),
  ('act-elliptical', 'Elliptical', 'cat_cardio', 'Cardio', 'Machine', 'cardio', 10, FALSE),
  ('act-stair-climber', 'Stair Climber', 'cat_cardio', 'Cardio', 'Machine', 'cardio', 10, FALSE),
  ('act-swimming', 'Swimming', 'cat_cardio', 'Cardio', 'Pool', 'cardio', 10, FALSE),
  ('act-hiit', 'HIIT', 'cat_cardio', 'Cardio', 'High Intensity', 'cardio', 10, FALSE),
  ('act-sprint-intervals', 'Sprint Intervals', 'cat_cardio', 'Cardio', 'Outdoor', 'cardio', 10, FALSE),
  ('act-hiking', 'Hiking', 'cat_cardio', 'Cardio', 'Nature', 'cardio', 10, FALSE),
  ('act-dancing', 'Dancing', 'cat_cardio', 'Cardio', 'General', 'cardio', 10, FALSE),
  ('act-boxing-cardio', 'Boxing Cardio', 'cat_cardio', 'Cardio', 'Combat', 'cardio', 10, FALSE),
  ('act-shadow-boxing', 'Shadow Boxing', 'cat_cardio', 'Cardio', 'Combat', 'cardio', 10, FALSE),
  ('act-aerobics', 'Aerobics', 'cat_cardio', 'Cardio', 'Group', 'cardio', 10, FALSE),
  ('act-burpees', 'Burpees', 'cat_cardio', 'Cardio', 'Bodyweight', 'cardio', 10, FALSE),
  ('act-mountain-climbers', 'Mountain Climbers', 'cat_cardio', 'Cardio', 'Bodyweight', 'cardio', 10, FALSE),
  ('act-jumping-jacks', 'Jumping Jacks', 'cat_cardio', 'Cardio', 'Bodyweight', 'cardio', 10, FALSE),
  ('act-high-knees', 'High Knees', 'cat_cardio', 'Cardio', 'Bodyweight', 'cardio', 10, FALSE),
  ('act-battle-ropes', 'Battle Ropes', 'cat_cardio', 'Cardio', 'Gym', 'cardio', 10, FALSE),
  ('act-kickboxing-cardio', 'Kickboxing Cardio', 'cat_cardio', 'Cardio', 'Combat', 'cardio', 10, FALSE),
  ('act-rowing', 'Rowing', 'cat_cardio', 'Cardio', 'Water', 'cardio', 10, FALSE),
  ('act-skipping', 'Skipping', 'cat_cardio', 'Cardio', 'Rope', 'cardio', 10, FALSE),
  ('act-incline-walk', 'Incline Walk', 'cat_cardio', 'Cardio', 'Treadmill', 'cardio', 10, FALSE),
  ('act-trail-running', 'Trail Running', 'cat_cardio', 'Cardio', 'Nature', 'cardio', 10, FALSE),
  ('act-spin-class', 'Spin Class', 'cat_cardio', 'Cardio', 'Group', 'cardio', 10, FALSE),
  ('act-circuit-training', 'Circuit Training', 'cat_cardio', 'Cardio', 'Gym', 'cardio', 10, FALSE),
  ('act-outdoor-run', 'Outdoor Run', 'cat_cardio', 'Cardio', 'Running', 'cardio', 10, FALSE),

  ('act-full-body-stretch', 'Full Body Stretch', 'cat_mobility', 'Stretching', 'Full Body', 'mobility', 10, FALSE),
  ('act-hamstring-stretch', 'Hamstring Stretch', 'cat_mobility', 'Stretching', 'Legs', 'mobility', 10, FALSE),
  ('act-quad-stretch', 'Quad Stretch', 'cat_mobility', 'Stretching', 'Legs', 'mobility', 10, FALSE),
  ('act-hip-flexor-stretch', 'Hip Flexor Stretch', 'cat_mobility', 'Stretching', 'Hips', 'mobility', 10, FALSE),
  ('act-shoulder-stretch', 'Shoulder Stretch', 'cat_mobility', 'Stretching', 'Shoulders', 'mobility', 10, FALSE),
  ('act-chest-stretch', 'Chest Stretch', 'cat_mobility', 'Stretching', 'Chest', 'mobility', 10, FALSE),
  ('act-back-stretch', 'Back Stretch', 'cat_mobility', 'Stretching', 'Back', 'mobility', 10, FALSE),
  ('act-neck-stretch', 'Neck Stretch', 'cat_mobility', 'Stretching', 'Neck', 'mobility', 10, FALSE),
  ('act-wrist-mobility', 'Wrist Mobility', 'cat_mobility', 'Mobility', 'Wrists', 'mobility', 10, FALSE),
  ('act-ankle-mobility', 'Ankle Mobility', 'cat_mobility', 'Mobility', 'Ankles', 'mobility', 10, FALSE),
  ('act-hip-mobility', 'Hip Mobility', 'cat_mobility', 'Mobility', 'Hips', 'mobility', 10, FALSE),
  ('act-thoracic-mobility', 'Thoracic Mobility', 'cat_mobility', 'Mobility', 'Back', 'mobility', 10, FALSE),
  ('act-yoga-flow', 'Yoga Flow', 'cat_mobility', 'Yoga', 'Full Body', 'mobility', 10, FALSE),
  ('act-sun-salutation', 'Sun Salutation', 'cat_mobility', 'Yoga', 'Full Body', 'mobility', 10, FALSE),
  ('act-child-pose', 'Child’s Pose', 'cat_mobility', 'Yoga', 'Back', 'mobility', 10, FALSE),
  ('act-downward-dog', 'Downward Dog', 'cat_mobility', 'Yoga', 'Full Body', 'mobility', 10, FALSE),
  ('act-cat-cow', 'Cat Cow', 'cat_mobility', 'Yoga', 'Spine', 'mobility', 10, FALSE),
  ('act-pigeon-pose', 'Pigeon Pose', 'cat_mobility', 'Yoga', 'Hips', 'mobility', 10, FALSE),
  ('act-cobra-stretch', 'Cobra Stretch', 'cat_mobility', 'Yoga', 'Back', 'mobility', 10, FALSE),
  ('act-foam-rolling', 'Foam Rolling', 'cat_mobility', 'Recovery', 'Full Body', 'mobility', 10, FALSE),
  ('act-dynamic-warm-up', 'Dynamic Warm Up', 'cat_mobility', 'Mobility', 'Full Body', 'mobility', 10, FALSE),
  ('act-cool-down-stretch', 'Cool Down Stretch', 'cat_mobility', 'Stretching', 'Full Body', 'mobility', 10, FALSE),
  ('act-butterfly-stretch', 'Butterfly Stretch', 'cat_mobility', 'Stretching', 'Hips', 'mobility', 10, FALSE),
  ('act-seated-forward-fold', 'Seated Forward Fold', 'cat_mobility', 'Stretching', 'Back', 'mobility', 10, FALSE),
  ('act-deep-squat-hold', 'Deep Squat Hold', 'cat_mobility', 'Mobility', 'Hips', 'mobility', 10, FALSE),
  ('act-calf-stretch', 'Calf Stretch', 'cat_mobility', 'Stretching', 'Legs', 'mobility', 10, FALSE),

  ('act-football', 'Football', 'cat_sports', 'Team', 'Outdoor', 'sports', 10, FALSE),
  ('act-basketball', 'Basketball', 'cat_sports', 'Team', 'Indoor', 'sports', 10, FALSE),
  ('act-badminton', 'Badminton', 'cat_sports', 'Racket', 'Indoor', 'sports', 10, FALSE),
  ('act-tennis', 'Tennis', 'cat_sports', 'Racket', 'Outdoor', 'sports', 10, FALSE),
  ('act-volleyball', 'Volleyball', 'cat_sports', 'Team', 'Indoor', 'sports', 10, FALSE),
  ('act-table-tennis', 'Table Tennis', 'cat_sports', 'Racket', 'Indoor', 'sports', 10, FALSE),
  ('act-swimming-sport', 'Swimming Sport', 'cat_sports', 'Individual', 'Pool', 'sports', 10, FALSE),
  ('act-boxing', 'Boxing', 'cat_sports', 'Combat', 'Ring', 'sports', 10, FALSE),
  ('act-martial-arts', 'Martial Arts', 'cat_sports', 'Combat', 'Dojo', 'sports', 10, FALSE),
  ('act-muay-thai', 'Muay Thai', 'cat_sports', 'Combat', 'Ring', 'sports', 10, FALSE),
  ('act-mma', 'MMA', 'cat_sports', 'Combat', 'Cage', 'sports', 10, FALSE),
  ('act-soccer', 'Soccer', 'cat_sports', 'Team', 'Outdoor', 'sports', 10, FALSE),
  ('act-futsal', 'Futsal', 'cat_sports', 'Team', 'Indoor', 'sports', 10, FALSE),
  ('act-rugby', 'Rugby', 'cat_sports', 'Team', 'Outdoor', 'sports', 10, FALSE),
  ('act-baseball', 'Baseball', 'cat_sports', 'Team', 'Outdoor', 'sports', 10, FALSE),
  ('act-cricket', 'Cricket', 'cat_sports', 'Team', 'Outdoor', 'sports', 10, FALSE),
  ('act-golf', 'Golf', 'cat_sports', 'Individual', 'Outdoor', 'sports', 10, FALSE),
  ('act-skateboarding', 'Skateboarding', 'cat_sports', 'Individual', 'Outdoor', 'sports', 10, FALSE),
  ('act-rock-climbing', 'Rock Climbing', 'cat_sports', 'Individual', 'Outdoor', 'sports', 10, FALSE),
  ('act-cycling-sport', 'Cycling Sport', 'cat_sports', 'Individual', 'Outdoor', 'sports', 10, FALSE),
  ('act-running-race', 'Running Race', 'cat_sports', 'Individual', 'Outdoor', 'sports', 10, FALSE),
  ('act-team-training', 'Team Training', 'cat_sports', 'Team', 'Practice', 'sports', 10, FALSE),
  ('act-skill-practice', 'Skill Practice', 'cat_sports', 'Individual', 'Practice', 'sports', 10, FALSE),
  ('act-sparring', 'Sparring', 'cat_sports', 'Combat', 'Practice', 'sports', 10, FALSE),
  ('act-handball', 'Handball', 'cat_sports', 'Team', 'Indoor', 'sports', 10, FALSE),
  ('act-squash', 'Squash', 'cat_sports', 'Racket', 'Indoor', 'sports', 10, FALSE)
ON DUPLICATE KEY UPDATE
  category_id = VALUES(category_id),
  muscle_group = VALUES(muscle_group),
  equipment = VALUES(equipment),
  exercise_type = VALUES(exercise_type),
  default_duration = VALUES(default_duration),
  is_custom = FALSE;
